# Generated by Django 2.2 on 2019-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='inj',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='ustsa_num',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
