# Generated by Django 2.2 on 2019-04-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0002_auto_20190426_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='racer_gender',
            field=models.CharField(choices=[('M', 0), ('F', 1)], default='NG', max_length=6),
        ),
    ]
