# Generated by Django 2.2 on 2019-04-27 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0003_racer_racer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=200)),
                ('race_date', models.DateField(verbose_name='Race Date')),
                ('location', models.CharField(max_length=200)),
                ('homoligation', models.CharField(default=0, max_length=200)),
                ('officials', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='racer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='racer',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='racer',
            name='last_name',
            field=models.CharField(default='last_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racer',
            name='racer_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='NG', max_length=6),
        ),
        migrations.CreateModel(
            name='RacerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_type', models.CharField(choices=[('CLR', 'Clear'), ('DNF', 'Did Not Finish'), ('DSQ', 'Disqualified'), ('DNS', 'Did Not Start')], default='CLR', max_length=3)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustsa_race_manager.Race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustsa_race_manager.Racer')),
            ],
        ),
    ]
