# Generated by Django 2.2 on 2019-05-29 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0006_auto_20190528_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racerresult',
            old_name='race_time',
            new_name='run_one_time',
        ),
        migrations.AddField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('SP', 'Sprint Classic'), ('CL', 'Classic'), ('PS', 'Parallel Sprint'), ('GS', 'Giant Slalom')], default='SP', max_length=2),
        ),
        migrations.AddField(
            model_name='racerresult',
            name='run_one_gate_penalties',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='racerresult',
            name='run_one_jump_penalties',
            field=models.DurationField(choices=[(datetime.timedelta(0), '0'), (datetime.timedelta(seconds=1), '1'), (datetime.timedelta(seconds=3), '3'), (datetime.timedelta(seconds=4), '4')], default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='racerresult',
            name='run_two_gate_penalties',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='racerresult',
            name='run_two_jump_penalties',
            field=models.DurationField(choices=[(datetime.timedelta(0), '0'), (datetime.timedelta(seconds=1), '1'), (datetime.timedelta(seconds=3), '3'), (datetime.timedelta(seconds=4), '4')], default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='racerresult',
            name='run_two_time',
            field=models.DurationField(default=datetime.timedelta(seconds=2400)),
        ),
    ]
