# Generated by Django 2.2 on 2019-05-29 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0007_auto_20190528_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerresult',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
