# Generated by Django 2.2 on 2019-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0010_auto_20190606_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='official',
            new_name='race_official',
        ),
        migrations.AddField(
            model_name='assignments',
            name='position',
            field=models.CharField(choices=[('ChiefRace', 'Chief of Race'), ('Datamanager', 'Data Manager'), ('Raceadmin', 'Race Administrator'), ('ChiefTiming', 'Chief of Timing'), ('Referee', 'Referee'), ('CourseChief', 'Course Chief'), ('StartReferee', 'Start Referee'), ('FinishReferee', 'Finish Referee')], default='CLR', max_length=3),
        ),
    ]
