# Generated by Django 2.2 on 2019-06-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0014_auto_20190608_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='position',
            field=models.CharField(choices=[('ChiefRace', 'Chief of Race'), ('Datamanager', 'Data Manager'), ('Raceadmin', 'Race Administrator'), ('ChiefTiming', 'Chief of Timing'), ('Referee', 'Referee'), ('CourseChief', 'Course Chief'), ('StartReferee', 'Start Referee'), ('FinishReferee', 'Finish Referee'), ('TD', 'Technical Delegate')], max_length=20),
        ),
    ]
