# Generated by Django 2.2 on 2019-06-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0015_auto_20190608_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPointsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=500)),
                ('season_code', models.PositiveIntegerField()),
                ('season_list_number', models.PositiveIntegerField()),
                ('start_race_date', models.DateField()),
                ('end_race_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('published', models.BooleanField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RacerPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_type', models.CharField(choices=[('SP', 'Sprint Classic'), ('CL', 'Classic'), ('PS', 'Parallel Sprint'), ('GS', 'Giant Slalom')], default='SP', max_length=2)),
                ('ustsa_points', models.DecimalField(decimal_places=3, default=500.0, max_digits=7)),
                ('position', models.PositiveIntegerField()),
                ('penalty', models.CharField(choices=[('+', 'Single Event Result'), ('*', 'No Results Since Base Season List'), ('>', 'No Results During Last Year'), (None, 'No Penalty Applied')], default='', max_length=2)),
                ('current_valid_list', models.BooleanField(default=False)),
                ('list_published', models.DateTimeField(auto_now_add=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustsa_race_manager.PublishedPointsList')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustsa_race_manager.Racer')),
            ],
        ),
    ]
