# Generated by Django 2.2 on 2019-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0017_auto_20190608_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='applied_penalty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
