# Generated by Django 2.2 on 2019-06-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0018_race_applied_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerresult',
            name='bib',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racerresult',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
