# Generated by Django 2.2 on 2019-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0019_auto_20190609_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerresult',
            name='applied_penalty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='racerresult',
            name='race_points',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='racerresult',
            name='race_result',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
