# Generated by Django 2.2 on 2019-06-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0021_auto_20190611_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racerpoints',
            old_name='list_id',
            new_name='points_list',
        ),
    ]
