# Generated by Django 2.2 on 2019-06-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustsa_race_manager', '0023_auto_20190611_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racerpoints',
            name='current_valid_list',
        ),
        migrations.AddField(
            model_name='publishedpointslist',
            name='current_valid_list',
            field=models.BooleanField(default=False),
        ),
    ]
